language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
#command to install python
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests

